load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "Smooth",
    sketch = "Smooth.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_blink"],
)
